SequenceGeneratorWeb/Controllers/SequenceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SequenceGnerator;
using SequenceGeneratorWeb.Models;
using System.Net;
using SequenceGeneratorWeb.Content;

namespace SequenceGeneratorWeb.Controllers
{
    public class SequenceController : Controller
    {
        private readonly IEnumerable<ISequenceGenerator> _generator;

        public SequenceController()
        {
            
        }

        public SequenceController(ISequenceGenerator[] generator)
        {
            _generator = generator;
        }
        
        // GET: Sequence
        public ActionResult Index(SequenceGeneratorModel model)
        {
            if (ModelState.IsValid && model.EndValue.HasValue)
            {
                model.Results = _generator.Select(c => new SequenceModel()
                {
                    Title = SequenceGeneratorDetails.ResourceManager.GetString(String.Format("{0}_Header", c.SequenceName)),
                    Description = SequenceGeneratorDetails.ResourceManager.GetString(String.Format("{0}_Description", c.SequenceName)),
                    Values = c.Generate(model.StartValue, model.EndValue.GetValueOrDefault(0))
                });
            }
            return View("Index", model);
        }

    }
}

SequenceGeneratorWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sequence Generator</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Hiral's Sequence Generator", "Index", "Sequence", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                  
                   
                </ul>
                
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sequence Generator</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>